batch_size: 4
data_path: C:/code/noodles/data

lr: 0.0001
reg_weight: 1e-4
d_model: 512
d_point: 256
shape_input_channels: 2
shape_enc_features: [32, 64, 128, 256, 512]
shape_spatial_shape: [64, 64, 64]
mix_nhead: 4
mix_nlayer: 4
occ_nhead: 8
occ_nlayer: 6
occ_mlp_size: 8
max_parts_length: 20
sample_num: 2000 #20000
colors:
  [
    "aliceblue",
    #"antiquewhite",
    "aquamarine",
    "azure",
    # "beige",
    "bisque",
    "black",
    #"blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dodgerblue",
    "firebrick",
    #"floralwhite",
    "forestgreen",
    #"gainsboro",
    #"ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    # "lightblue",
    # "lightcoral",
    # "lightcyan",
    # "lightgoldenrodyellow",
    # "lightgray",
    # "lightgreen",
    # "lightpink",
    # "lightsalmon",
    # "lightseagreen",
    # "lightskyblue",
    # "lightslategray",
    # "lightsteelblue",
    # "lightyellow",
    "lime",
    "limegreen",
    #"linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    #"navajowhite",
    "navy",
    #"oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "paraview_background",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "raw_sienna",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    #"seashell",
    "sienna",
    #"silver",
    "skyblue",
    "slateblue",
    "slategray",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    #"white",
    #"whitesmoke",
    "yellow",
    "yellowgreen",
    "tab:blue",
    "tab:orange",
    "tab:green",
    "tab:red",
    "tab:purple",
    "tab:brown",
    "tab:pink",
    "tab:gray",
    "tab:olive",
    "tab:cyan",
  ]
